### ISSUE TITLE
Line 110 syntax error in Python 3.7.3

### ISSUE THREAD

**Issue by stafford23** [samapriya/Planet-Mosaic-Quads-Download-CLI#2]
C:\Users\Tony Stafford\Documents\PBASEMAPS\Planet-Mosaic-Quads-Download-CLI-master\pbasemap>python pbasemap.py -h
 File "pbasemap.py", line 110
   usage: pbasemap.py [-h] {rbox,mosaic_list,download,mpdownload,shp2geojson} ...
                           ^
SyntaxError: invalid syntax

**Comment by samapriya** [comment]
Could not replicate this issue, closing for now
